# Generated by Django 3.2.18 on 2023-10-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_contact_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='marital_status',
            field=models.CharField(default='s', max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telnumber',
            field=models.CharField(max_length=20),
        ),
    ]
