# Generated by Django 3.2.18 on 2023-10-26 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_contact_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telnumber',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Only digits are allowed.", regex='^\\d+$')]),
        ),
    ]
