# Generated by Django 3.2.18 on 2023-10-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_auto_20231026_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='marital_status',
            field=models.CharField(choices=[('s', 'Single'), ('d', 'Divorced'), ('m', 'Married')], default='s', max_length=1),
            preserve_default=False,
        ),
    ]
